### ISSUE TITLE
ValueError: Empty results file; perhaps invalid query

### ISSUE THREAD

**Issue by sunwanying21** [gamcil/synthaser#11]
Hello,

I run this command and get these errors. Could you please help me to figure it out? Thanks a lot. 

command: 
synthaser search  -qf a_sixpack_rename.fa -o  a_cdd.out --evalue 0.01

errors: 
`Traceback (most recent call last):
  File "/home/sunwanying/.local/lib/python3.8/site-packages/synthaser/search.py", line 123, in search
    with open(results_file) as rf:
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sunwanying/.local/lib/python3.8/site-packages/synthaser/main.py", line 65, in synthaser
    synthases = search.search(
  File "/home/sunwanying/.local/lib/python3.8/site-packages/synthaser/search.py", line 134, in search
    handle = _remote(
  File "/home/sunwanying/.local/lib/python3.8/site-packages/synthaser/search.py", line 169, in _remote
    response = ncbi.retrieve(cdsid, delay=delay, max_retries=max_retries)
  File "/home/sunwanying/.local/lib/python3.8/site-packages/synthaser/ncbi.py", line 202, in retrieve
    finished = check(cdsid)
  File "/home/sunwanying/.local/lib/python3.8/site-packages/synthaser/ncbi.py", line 112, in check
    raise ValueError("Empty results file; perhaps invalid query?")
ValueError: Empty results file; perhaps invalid query?`

**Comment by lisadriani** [comment]
I had the same issue! Did anything solve it?
